<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice {{ $invoice->invoice_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111; }
        .container { width: 100%; padding: 20px; }
        .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 20px; }
        .brand h1 { margin: 0; font-size: 22px; }
        .brand p { margin: 3px 0 0; color: #555; }
        .box { border: 1px solid #ddd; padding: 12px; border-radius: 6px; }
        .muted { color: #666; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { padding: 10px; border-bottom: 1px solid #eee; text-align: left; }
        th { background: #f5f5f5; font-weight: 700; }
        .total-row td { font-weight: 700; }
        .right { text-align: right; }
        .mt { margin-top: 16px; }
        .small { font-size: 11px; color: #666; }
    </style>
</head>
<body>
@php
    $appt = $invoice->appointment;
    $veh = $appt?->vehicle;
    $cust = $appt?->user;
@endphp

<div class="container">
    <div class="header">
        <div class="brand">
            <h1>AutoServe</h1>
            <p class="muted">Garage Management System</p>
        </div>
        <div class="box">
            <div><strong>Invoice:</strong> {{ $invoice->invoice_number }}</div>
            <div><strong>Date:</strong> {{ $invoice->created_at->format('d M Y') }}</div>
            <div><strong>Status:</strong> Paid/Generated</div>
        </div>
    </div>

    <div style="display:flex; gap:12px;">
        <div class="box" style="flex:1;">
            <div class="muted" style="margin-bottom:6px;"><strong>Billed To</strong></div>
            <div><strong>{{ $cust?->name ?? 'Customer' }}</strong></div>
            <div class="muted">{{ $cust?->email ?? '' }}</div>
        </div>

        <div class="box" style="flex:1;">
            <div class="muted" style="margin-bottom:6px;"><strong>Service Details</strong></div>
            <div><strong>Service:</strong> {{ $appt?->service_type ?? 'Service' }}</div>
            <div><strong>Date:</strong> {{ $appt?->service_date ?? '—' }} {{ $appt?->service_time ? ' • '.$appt->service_time : '' }}</div>
            <div><strong>Vehicle:</strong>
                {{ $veh ? trim(($veh->brand ?? '').' '.($veh->model ?? '')) : '—' }}
                {{ $veh?->plate_number ? ' • '.$veh->plate_number : '' }}
            </div>
        </div>
    </div>

    <div class="mt box">
        <div class="muted"><strong>Charges</strong></div>

        <table>
            <thead>
                <tr>
                    <th>Description</th>
                    <th class="right">Amount (₹)</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Labor Cost</td>
                    <td class="right">{{ number_format((float)$invoice->labor_cost, 2) }}</td>
                </tr>
                <tr>
                    <td>Parts Cost</td>
                    <td class="right">{{ number_format((float)$invoice->parts_cost, 2) }}</td>
                </tr>
                <tr class="total-row">
                    <td>Total</td>
                    <td class="right">{{ number_format((float)$invoice->total_amount, 2) }}</td>
                </tr>
            </tbody>
        </table>

        @if($invoice->notes)
            <div class="mt">
                <div class="muted"><strong>Notes</strong></div>
                <div>{{ $invoice->notes }}</div>
            </div>
        @endif
    </div>

    <div class="mt small">
        This invoice was generated by AutoServe. Thank you for choosing our service.
    </div>
</div>

</body>
</html>